### ISSUE TITLE
Speed slider doesn't set 100%

### ISSUE THREAD

**Issue by fpw** [flandreas/antares-source#10]
Not sure if it's intentional, so not posting in public: but if I drag the simulation speed slider to 100%, it's set back to 99% internally, preventing Antares from activating the faster approach with steps per 20 ms instead of `STEPS_NON_MAX`.

I see this in the log when dragging the slider to 100 (increased the log level of that message to info):
````
2024-04-24 17:04:52,505  INFO [AWT-EventQueue-0] (SystemSpeed.kt:36) - System speed 100
2024-04-24 17:04:52,505  INFO [AWT-EventQueue-0] (SystemSpeed.kt:36) - System speed 99
````

Edit: The reason is that the slider has `snapToTicks = true`, there are 101 values in the slider (0 .. 100, inclusive), so having 33 major and 3 minor marks will snap to 99.

**Comment by flandreas** [comment]
Oh great! My "Tanenbaum" computer example now calculates the sum 0..100 on my machine in 1 second instead of 6 seconds as before.
